### ISSUE TITLE
TestSPFunctional Failed

### ISSUE THREAD

**Issue by bq1024** [bnb-chain/greenfield-sp-standard-test#19]
The functional verification tests  failed with 403 error

```
$ cat config.yml 
# this is greenfield testnet configuration
GreenfieldEndpoint: https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org:443
GreenfieldChainId: greenfield_5600-1

# private key: RootAcc  need have BNB balance
# TODO: replace to yourself private key
RootAcc: my_private_key
#  If you do not provide a value for TestAcc, the test process will automatically generate a TestAcc private key using RootAcc. Please note that RootAcc is mandatory.
TestAcc:

# TODO: replace to you want to test SP operator address
SPOperatorAddr: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4 
# performance test params
TPS: 2
# Number of users. If the user.csv file does not exist or contains fewer accounts than the configured value, new account private keys will be automatically generated and saved in the user.csv file.
NumUsers: 10
# performance test duration(seconds)
Duration: 60
Upload: true
Download: true
# file size(bytes) random ~10kb(FileSize + random(10*1024))
FileSize: 1024
# cross-origin headers verify info
HttpHeaders:
  Access-Control-Allow-Headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-MD5,Range,Authorization,X-Gnfd-Content-Sha256,X-Gnfd-Unsigned-Msg,X-Gnfd-Txn-Hash,Date,X-Gnfd-Object-ID,X-Gnfd-Resource,X-Gnfd-Piece-Index,X-Gnfd-Redundancy-Index,Address,X-Gnfd-User-Address,X-Gnfd-App-Domain,X-Gnfd-App-Reg-Nonce,X-Gnfd-Date,X-Gnfd-App-Reg-Public-Key,X-Gnfd-App-Reg-Expiry-Date
  Access-Control-Allow-Origin: '*'
  Access-Control-Allow-Methods: GET,PUT,POST,DELETE,PATCH,OPTIONS
  Referrer-Policy: origin-when-cross-origin
#  Access-Control-Expose-Headers: '*'
```

```
$ go test -v -run TestSPFunctional -timeout 30m
2023/10/27 18:43:22.935381 [INFO] GID 1, config.go:43 ===config file: /home/nbfs/greenfield-sp-standard-test/config/config.yml ===
=== RUN   TestSPFunctional
2023/10/27 18:43:23.114048 [INFO] GID 98, basesuite.go:28 rootAccountBalance: 27.779BNB , root account : 0x8FF2279eD13c6B335CDd4E5789b8dC26a9a178bD
2023/10/27 18:43:23.268422 [INFO] GID 98, account.go:45 new private key:149f0d11f97363d6c69a6f3376a1960d6fc084d1b11c8b8a12b6a052c76618b2
2023/10/27 18:43:23.449385 [INFO] GID 98, basesuite.go:57 Transfer BNB to: 0x70430fa9307557241856B2EfB85d2272891f5043, tx hash: C543F1C3B622439601A9DD3CABBCB863AD7D6C66200FFC30F96E2A0B3EACE076
2023/10/27 18:43:25.669058 [INFO] GID 98, account.go:83 sp operator address: 0x89A1CC91B642DECbC4789474694C606E0E0c420b, endpoint: https://gnfd-testnet-sp1.bnbchain.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669115 [INFO] GID 98, account.go:83 sp operator address: 0x03A42215dC678E65A145B3E18e84046a959DC11F, endpoint: https://gnfd-testnet-sp2.bnbchain.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669150 [INFO] GID 98, account.go:83 sp operator address: 0x5ccF0F6b78a37Ef4e2CcBC10D155c28Fb8bE9BaF, endpoint: https://gnfd-testnet-sp3.bnbchain.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669185 [INFO] GID 98, account.go:83 sp operator address: 0x08975d0AFDE4bc8BE3501B517Feec2d6c2b2bdaa, endpoint: https://gnfd-testnet-sp4.bnbchain.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669220 [INFO] GID 98, account.go:83 sp operator address: 0xBB0cac4668D970db8B51B6C1F80E6627f2Bd3c02, endpoint: https://gnfd-testnet-sp1.nodereal.io, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669254 [INFO] GID 98, account.go:83 sp operator address: 0x2a15da875b1bA0F82eb3A67ae027f5844915bA5a, endpoint: https://gnfd-testnet-sp2.nodereal.io, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669287 [INFO] GID 98, account.go:83 sp operator address: 0x5FFf5A6c94b182fB965B40C7B9F30199b969eD2f, endpoint: https://gnfd-testnet-sp3.nodereal.io, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669320 [INFO] GID 98, account.go:83 sp operator address: 0xDA8EC34bBF3641Dc966e20B8aCB6f51b0bd16Bc2, endpoint: https://gnfd-testnet-sp.epotter-qa.io, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669354 [INFO] GID 98, account.go:83 sp operator address: 0x4d23aAE960F32e52DB875F785A8cFd6eCF10fE7d, endpoint: https://sp0.bluebots.net, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669405 [INFO] GID 98, account.go:83 sp operator address: 0x80c0d7E368A1B3a9be86f8D41A98a6a67dD51FDd, endpoint: https://gnfd-testnet-sp-1.blockvision.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669477 [INFO] GID 98, account.go:83 sp operator address: 0xb202B21c34c60A47AA343CA8F7F8183A78Ca1459, endpoint: https://gnfd-testnet.Atomstaking.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669512 [INFO] GID 98, account.go:83 sp operator address: 0xC22843908F8c82962754dC141F44Aa73E2C2A74E, endpoint: https://gnfd-testnet.wav3.net, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669546 [INFO] GID 98, account.go:83 sp operator address: 0x5798dfCC1851295328ed4531F67D12E0B2703366, endpoint: https://gnfd-sp.4everland.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669580 [INFO] GID 98, account.go:83 sp operator address: 0xe66856A04BA49E8D60Fa090661f53e1014be84dC, endpoint: https://greenfield-sp.4everland.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669614 [INFO] GID 98, account.go:83 sp operator address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4, endpoint: https://sptestnet.nebulablock.com, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/27 18:43:25.669652 [INFO] GID 98, basesuite.go:43 SP Endpoint: https://sptestnet.nebulablock.com, address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
=== RUN   TestSPFunctional/Test_00_SystemStatus
2023/10/27 18:43:25.732812 [INFO] GID 118, func_test.go:56 statusInfo: {"status":{"storage_provider_info":{"sp_code_version":"v1.0.1","sp_code_commit":"ae61ba06c481de00ccaada95999d41d7ef541ed5","sp_architecture":"amd64","sp_go_version":"go1.20.3","sp_operating_system":"linux","sp_operator_address":"0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4","sp_domain_name":"sptestnet.nebulablock.com"},"block_syncer_info":{"bs_block_height":"1699336","bs_block_hash":"0xa12ba91c141c9613ec39b9b6b7b35e09b3eecf1828cffc0f94ae51c16f947b37","bs_update_time":"1698432195","bs_mysql_version":"8.0.34-0ubuntu0.20.04.1","bs_default_character_set_name":"utf8mb4","bs_default_collation_name":"utf8mb4_unicode_ci","bs_modules":["epoch","bucket","object","payment","group","permission","storage_provider","prefix_tree","virtual_group","sp_exit_events","object_id_map"],"bs_workers":50,"bs_enable_dual_db":false},"chain_info":{"chain_id":"greenfield_5600-1","chain_address":["https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org:443","https://gnfd-testnet-fullnode-tendermint-ap.bnbchain.org:443"]}}}
2023/10/27 18:43:25.732888 [INFO] GID 118, func_test.go:57 headers: &map[Access-Control-Allow-Headers:[*] Access-Control-Allow-Methods:[*] Access-Control-Allow-Origin:[*] Access-Control-Expose-Headers:[*] Connection:[keep-alive] Content-Length:[1007] Content-Type:[application/json] Date:[Fri, 27 Oct 2023 18:43:25 GMT] Server:[nginx/1.18.0 (Ubuntu)]]
2023/10/27 18:43:25.732935 [ERROR] GID 118, http.go:71 headerKey: Referrer-Policy, respValues: , expectValue: origin-when-cross-origin
    func_test.go:58: 
        	Error Trace:	/home/nbfs/greenfield-sp-standard-test/func_test.go:58
        	Error:      	Should be true
        	Test:       	TestSPFunctional/Test_00_SystemStatus
2023/10/27 18:43:25.780217 [INFO] GID 118, func_test.go:65 blockSyncHeight: 1699336, blockChain LatestBlockHeight: 1699337
=== RUN   TestSPFunctional/Test_01_UploadMultiSizeFile
{"level":"error","time":"2023-10-27T18:43:25Z","message":"do API error, url: https://sptestnet.nebulablock.com/greenfield/admin/v1/get-approval?action=CreateBucket, err: statusCode 403 : code : 50029  (Message: sp is not in service status)"}
    func_test.go:73: 
        	Error Trace:	/home/nbfs/greenfield-sp-standard-test/func_test.go:73
        	Error:      	Received unexpected error:
        	            	statusCode 403 : code : 50029  (Message: sp is not in service status)
        	Test:       	TestSPFunctional/Test_01_UploadMultiSizeFile
2023/10/27 18:43:25.860035 [INFO] GID 124, func_test.go:74 Created bucket: gb6dz, txHash: 
    func_test.go:76: 
        	Error Trace:	/home/nbfs/greenfield-sp-standard-test/func_test.go:76
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = No such bucket: unknown request
        	Test:       	TestSPFunctional/Test_01_UploadMultiSizeFile
        	Messages:   	BuyQuotaForBucket error
2023/10/27 18:43:25.901300 [INFO] GID 124, func_test.go:77 BuyQuotaForBucket bucket: gb6dz, txHash: 
=== RUN   TestSPFunctional/Test_01_UploadMultiSizeFile/Put_1B_file
{"level":"error","time":"2023-10-27T18:43:25Z","message":"route endpoint by bucket: gb6dz failed, err: rpc error: code = Unknown desc = No such bucket: unknown request"}
    func_test.go:96: 
        	Error Trace:	/home/nbfs/greenfield-sp-standard-test/func_test.go:96
        	            				/home/nbfs/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = No such bucket: unknown request
        	Test:       	TestSPFunctional/Test_01_UploadMultiSizeFile/Put_1B_file
2023/10/27 18:43:25.975768 [INFO] GID 125, func_test.go:97 Created object - file size: 1 bytes, endpoint: https://sptestnet.nebulablock.com, tx: 
2023/10/27 18:43:25.975801 [INFO] GID 125, func_test.go:99 Uploading file - object: 5e22rl94t1, bucket: gb6dz
--- FAIL: TestSPFunctional (3.04s)
    --- FAIL: TestSPFunctional/Test_00_SystemStatus (0.11s)
    --- FAIL: TestSPFunctional/Test_01_UploadMultiSizeFile (0.20s)
        --- FAIL: TestSPFunctional/Test_01_UploadMultiSizeFile/Put_1B_file (0.07s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1502347]

goroutine 125 [running]:
testing.tRunner.func1.2({0x1703820, 0x27ac020})
	/usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0x1703820, 0x27ac020})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/bnb-chain/greenfield-sp-standard-test_test.(*SPFunctionalTestSuite).Test_01_UploadMultiSizeFile.func1()
	/home/nbfs/greenfield-sp-standard-test/func_test.go:100 +0x267
github.com/stretchr/testify/suite.(*Suite).Run.func2(0xc001602d00?)
	/home/nbfs/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112 +0x36
testing.tRunner(0xc001603a00, 0xc001c06e70)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x3ea
exit status 2
FAIL	github.com/bnb-chain/greenfield-sp-standard-test	3.127s
```

**Comment by STdevK** [comment]
Hi there, did you submit a proposal to become SP on Greenfield Testnet?

**Comment by bq1024** [comment]
> Hi there, did you submit a proposal to become SP on Greenfield Testnet?

Yes I did. This one: https://testnet.greenfieldscan.com/proposal/48

**Comment by MockY-B** [comment]
1. Test_00_SystemStatus failed with response header missed "headerKey:Referrer-Policy"
2. Test_01_UploadMultiSizeFile failed with not maintenance account to createBucket(need use maintenance test account 0x6f3D7fd813C6aF8c49c9A57D8f3088B6494259ce to test), new sp default is maintenance status

**Comment by bq1024** [comment]
> 1. Test_00_SystemStatus failed with response header missed "headerKey:Referrer-Policy"
> 2. Test_01_UploadMultiSizeFile failed with not maintenance account to createBucket(need use maintenance test account 0x6f3D7fd813C6aF8c49c9A57D8f3088B6494259ce to test), new sp default is maintenance status

Thank you! The first issue was resolved.
I tried with the correct maintenance account, but the problem still persists. Please advise on how to fix it, thanks.
```
2023/10/30 17:40:14.680215 [INFO] GID 1, config.go:43 ===config file: /home/nbfs/greenfield-sp-standard-test/config/config.yml ===
=== RUN   TestSPFunctional
2023/10/30 17:40:14.952989 [INFO] GID 29, basesuite.go:28 rootAccountBalance: 4.979BNB , root account : 0x6f3D7fd813C6aF8c49c9A57D8f3088B6494259ce
2023/10/30 17:40:15.130568 [INFO] GID 29, account.go:45 new private key:3e049453ad7a372508e057e8e70cd7815b07eacd9a125f133f2b49655b6d5ab3
2023/10/30 17:40:15.309238 [INFO] GID 29, basesuite.go:57 Transfer BNB to: 0x8431d02A71A5a6586DA5896C75f4766f138B660C, tx hash: CB1AC0BAC03850DAF8EABA42457304AFD67335D44D1885C0A0DC0F5CB4F26032
2023/10/30 17:40:18.502117 [INFO] GID 29, account.go:83 sp operator address: 0x89A1CC91B642DECbC4789474694C606E0E0c420b, endpoint: https://gnfd-testnet-sp1.bnbchain.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502172 [INFO] GID 29, account.go:83 sp operator address: 0x03A42215dC678E65A145B3E18e84046a959DC11F, endpoint: https://gnfd-testnet-sp2.bnbchain.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502207 [INFO] GID 29, account.go:83 sp operator address: 0x5ccF0F6b78a37Ef4e2CcBC10D155c28Fb8bE9BaF, endpoint: https://gnfd-testnet-sp3.bnbchain.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502242 [INFO] GID 29, account.go:83 sp operator address: 0x08975d0AFDE4bc8BE3501B517Feec2d6c2b2bdaa, endpoint: https://gnfd-testnet-sp4.bnbchain.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502275 [INFO] GID 29, account.go:83 sp operator address: 0xBB0cac4668D970db8B51B6C1F80E6627f2Bd3c02, endpoint: https://gnfd-testnet-sp1.nodereal.io, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502308 [INFO] GID 29, account.go:83 sp operator address: 0x2a15da875b1bA0F82eb3A67ae027f5844915bA5a, endpoint: https://gnfd-testnet-sp2.nodereal.io, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502341 [INFO] GID 29, account.go:83 sp operator address: 0x5FFf5A6c94b182fB965B40C7B9F30199b969eD2f, endpoint: https://gnfd-testnet-sp3.nodereal.io, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502374 [INFO] GID 29, account.go:83 sp operator address: 0xDA8EC34bBF3641Dc966e20B8aCB6f51b0bd16Bc2, endpoint: https://gnfd-testnet-sp.epotter-qa.io, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502409 [INFO] GID 29, account.go:83 sp operator address: 0x4d23aAE960F32e52DB875F785A8cFd6eCF10fE7d, endpoint: https://sp0.bluebots.net, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502445 [INFO] GID 29, account.go:83 sp operator address: 0x80c0d7E368A1B3a9be86f8D41A98a6a67dD51FDd, endpoint: https://gnfd-testnet-sp-1.blockvision.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502477 [INFO] GID 29, account.go:83 sp operator address: 0xb202B21c34c60A47AA343CA8F7F8183A78Ca1459, endpoint: https://gnfd-testnet.Atomstaking.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502527 [INFO] GID 29, account.go:83 sp operator address: 0xC22843908F8c82962754dC141F44Aa73E2C2A74E, endpoint: https://gnfd-testnet.wav3.net, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502560 [INFO] GID 29, account.go:83 sp operator address: 0x5798dfCC1851295328ed4531F67D12E0B2703366, endpoint: https://gnfd-sp.4everland.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502606 [INFO] GID 29, account.go:83 sp operator address: 0xe66856A04BA49E8D60Fa090661f53e1014be84dC, endpoint: https://greenfield-sp.4everland.org, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502639 [INFO] GID 29, account.go:83 sp operator address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4, endpoint: https://sptestnet.nebulablock.com, config sp address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
2023/10/30 17:40:18.502679 [INFO] GID 29, basesuite.go:43 SP Endpoint: https://sptestnet.nebulablock.com, address: 0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4
=== RUN   TestSPFunctional/Test_00_SystemStatus
2023/10/30 17:40:18.551534 [INFO] GID 31, func_test.go:56 statusInfo: {"status":{"storage_provider_info":{"sp_code_version":"v1.0.1","sp_code_commit":"ae61ba06c481de00ccaada95999d41d7ef541ed5","sp_architecture":"amd64","sp_go_version":"go1.20.3","sp_operating_system":"linux","sp_operator_address":"0x1cACD93bd2D511bce13534bD8690E5bDD3D894C4","sp_domain_name":"sptestnet.nebulablock.com"},"block_syncer_info":{"bs_block_height":"1772854","bs_block_hash":"0x0587a00ee16a19ae2273e6e656c965f0a6d2e1eedb1ccbafc8eec40da4712425","bs_update_time":"1698687614","bs_mysql_version":"8.0.34-0ubuntu0.20.04.1","bs_default_character_set_name":"utf8mb4","bs_default_collation_name":"utf8mb4_unicode_ci","bs_modules":["epoch","bucket","object","payment","group","permission","storage_provider","prefix_tree","virtual_group","sp_exit_events","object_id_map"],"bs_workers":50,"bs_enable_dual_db":false},"chain_info":{"chain_id":"greenfield_5600-1","chain_address":["https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org:443","https://gnfd-testnet-fullnode-tendermint-ap.bnbchain.org:443"]}}}
2023/10/30 17:40:18.551628 [INFO] GID 31, func_test.go:57 headers: &map[Access-Control-Allow-Credentials:[true] Access-Control-Allow-Headers:[*] Access-Control-Allow-Methods:[*] Access-Control-Allow-Origin:[*] Access-Control-Expose-Headers:[*] Connection:[keep-alive] Content-Length:[1007] Content-Type:[application/json] Date:[Mon, 30 Oct 2023 17:40:18 GMT] Referrer-Policy:[origin-when-cross-origin] Server:[nginx/1.18.0 (Ubuntu)]]
2023/10/30 17:40:18.597449 [INFO] GID 31, func_test.go:65 blockSyncHeight: 1772854, blockChain LatestBlockHeight: 1772854
=== RUN   TestSPFunctional/Test_01_UploadMultiSizeFile
{"level":"error","time":"2023-10-30T17:40:18Z","message":"do API error, url: https://sptestnet.nebulablock.com/greenfield/admin/v1/get-approval?action=CreateBucket, err: statusCode 403 : code : 50029  (Message: sp is not in service status)"}
    func_test.go:73: 
        	Error Trace:	/home/nbfs/greenfield-sp-standard-test/func_test.go:73
        	Error:      	Received unexpected error:
        	            	statusCode 403 : code : 50029  (Message: sp is not in service status)
        	Test:       	TestSPFunctional/Test_01_UploadMultiSizeFile
2023/10/30 17:40:18.867740 [INFO] GID 105, func_test.go:74 Created bucket: 5sdln, txHash: 
    func_test.go:76: 
        	Error Trace:	/home/nbfs/greenfield-sp-standard-test/func_test.go:76
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = No such bucket: unknown request
        	Test:       	TestSPFunctional/Test_01_UploadMultiSizeFile
        	Messages:   	BuyQuotaForBucket error
2023/10/30 17:40:18.904167 [INFO] GID 105, func_test.go:77 BuyQuotaForBucket bucket: 5sdln, txHash: 
=== RUN   TestSPFunctional/Test_01_UploadMultiSizeFile/Put_1B_file
{"level":"error","time":"2023-10-30T17:40:18Z","message":"route endpoint by bucket: 5sdln failed, err: rpc error: code = Unknown desc = No such bucket: unknown request"}
    func_test.go:96: 
        	Error Trace:	/home/nbfs/greenfield-sp-standard-test/func_test.go:96
        	            				/home/nbfs/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = No such bucket: unknown request
        	Test:       	TestSPFunctional/Test_01_UploadMultiSizeFile/Put_1B_file
2023/10/30 17:40:18.987057 [INFO] GID 130, func_test.go:97 Created object - file size: 1 bytes, endpoint: https://sptestnet.nebulablock.com, tx: 
2023/10/30 17:40:18.987090 [INFO] GID 130, func_test.go:99 Uploading file - object: 4xex9g22mu, bucket: 5sdln
--- FAIL: TestSPFunctional (4.31s)
    --- PASS: TestSPFunctional/Test_00_SystemStatus (0.09s)
    --- FAIL: TestSPFunctional/Test_01_UploadMultiSizeFile (0.39s)
        --- FAIL: TestSPFunctional/Test_01_UploadMultiSizeFile/Put_1B_file (0.08s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1502347]

goroutine 130 [running]:
testing.tRunner.func1.2({0x1703820, 0x27ac020})
	/usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0x1703820, 0x27ac020})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/bnb-chain/greenfield-sp-standard-test_test.(*SPFunctionalTestSuite).Test_01_UploadMultiSizeFile.func1()
	/home/nbfs/greenfield-sp-standard-test/func_test.go:100 +0x267
github.com/stretchr/testify/suite.(*Suite).Run.func2(0xc00069a7d0?)
	/home/nbfs/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112 +0x36
testing.tRunner(0xc0012b7ba0, 0xc0019b2210)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x3ea
exit status 2
FAIL	github.com/bnb-chain/greenfield-sp-standard-test	4.390s
```

**Comment by bq1024** [comment]
Need to activate the SP before doing the test. Close the issue.
